export let role = "admin";

export const apiUrl = process.env.NEXT_PUBLIC_API_URL;

export const employeeData = [
  {
    "id": "EMP001",
    "name": "Alice Johnson",
    "phone": "+1-202-555-0147",
    "email": "alice.johnson@example.com",
    "address": "123 Maple Street, Springfield, IL, USA",
    "jobTitle": "Software Engineer",
    "department": "Engineering",
    "joiningDate": "2021-03-15",
    "isPresentToday": true,
    "salary": 85000,
    "manager": "Robert Smith",
    "photo": "https://randomuser.me/api/portraits/women/1.jpg"
  },
  {
    "id": "EMP002",
    "name": "Michael Brown",
    "phone": "+1-202-555-0189",
    "email": "michael.brown@example.com",
    "address": "456 Oak Avenue, Austin, TX, USA",
    "jobTitle": "HR Manager",
    "department": "Human Resources",
    "joiningDate": "2019-07-01",
    "isPresentToday": true,
    "salary": 95000,
    "manager": "N/A",
    "photo": "https://randomuser.me/api/portraits/men/2.jpg"
  },
  {
    "id": "EMP003",
    "name": "Sophia Martinez",
    "phone": "+1-202-555-0123",
    "email": "sophia.martinez@example.com",
    "address": "789 Pine Road, Denver, CO, USA",
    "jobTitle": "Marketing Specialist",
    "department": "Marketing",
    "joiningDate": "2022-11-10",
    "isPresentToday": true,
    "salary": 67000,
    "manager": "Emily Davis",
    "photo": "https://randomuser.me/api/portraits/women/3.jpg"
  },
  {
    "id": "EMP004",
    "name": "David Wilson",
    "phone": "+1-202-555-0199",
    "email": "david.wilson@example.com",
    "address": "321 Birch Blvd, Seattle, WA, USA",
    "jobTitle": "Accountant",
    "department": "Finance",
    "joiningDate": "2020-05-20",
    "isPresentToday": true,
    "salary": 72000,
    "manager": "Laura Green",
    "photo": "https://randomuser.me/api/portraits/men/4.jpg"
  },
  {
    "id": "EMP005",
    "name": "Emma Thompson",
    "phone": "+1-202-555-0172",
    "email": "emma.thompson@example.com",
    "address": "654 Cedar Lane, Miami, FL, USA",
    "jobTitle": "Project Manager",
    "department": "Operations",
    "joiningDate": "2018-09-12",
    "isPresentToday": true,
    "salary": 105000,
    "manager": "Robert Smith",
    "photo": "https://randomuser.me/api/portraits/women/5.jpg"
  },
  {
    "id": "EMP006",
    "name": "James Anderson",
    "phone": "+1-202-555-0156",
    "email": "james.anderson@example.com",
    "address": "987 Elm Street, Boston, MA, USA",
    "jobTitle": "Business Analyst",
    "department": "Business Intelligence",
    "joiningDate": "2021-06-25",
    "isPresentToday": true,
    "salary": 80000,
    "manager": "Laura Green",
    "photo": "https://randomuser.me/api/portraits/men/6.jpg"
  },
  {
    "id": "EMP007",
    "name": "Olivia Taylor",
    "phone": "+1-202-555-0110",
    "email": "olivia.taylor@example.com",
    "address": "741 Willow Drive, San Diego, CA, USA",
    "jobTitle": "UI/UX Designer",
    "department": "Design",
    "joiningDate": "2020-08-17",
    "isPresentToday": false,
    "salary": 75000,
    "manager": "Robert Smith",
    "photo": "https://randomuser.me/api/portraits/women/7.jpg"
  },
  {
    "id": "EMP008",
    "name": "Daniel Harris",
    "phone": "+1-202-555-0165",
    "email": "daniel.harris@example.com",
    "address": "852 Lakeview Rd, Orlando, FL, USA",
    "jobTitle": "DevOps Engineer",
    "department": "Engineering",
    "joiningDate": "2022-02-01",
    "isPresentToday": true,
    "salary": 88000,
    "manager": "Alice Johnson",
    "photo": "https://randomuser.me/api/portraits/men/8.jpg"
  },
  {
    "id": "EMP009",
    "name": "Grace Lee",
    "phone": "+1-202-555-0190",
    "email": "grace.lee@example.com",
    "address": "963 Park Lane, Chicago, IL, USA",
    "jobTitle": "Recruiter",
    "department": "Human Resources",
    "joiningDate": "2019-12-05",
    "isPresentToday": true,
    "salary": 62000,
    "manager": "Michael Brown",
    "photo": "https://randomuser.me/api/portraits/women/9.jpg"
  },
  {
    "id": "EMP010",
    "name": "William Clark",
    "phone": "+1-202-555-0104",
    "email": "william.clark@example.com",
    "address": "147 Aspen Way, Dallas, TX, USA",
    "jobTitle": "Sales Executive",
    "department": "Sales",
    "joiningDate": "2020-10-11",
    "isPresentToday": false,
    "salary": 70000,
    "manager": "Emily Davis",
    "photo": "https://randomuser.me/api/portraits/men/10.jpg"
  },
  {
    "id": "EMP011",
    "name": "Ava White",
    "phone": "+1-202-555-0183",
    "email": "ava.white@example.com",
    "address": "258 Walnut St, New York, NY, USA",
    "jobTitle": "Content Writer",
    "department": "Marketing",
    "joiningDate": "2022-07-08",
    "isPresentToday": true,
    "salary": 60000,
    "manager": "Sophia Martinez",
    "photo": "https://randomuser.me/api/portraits/women/11.jpg"
  },
  {
    "id": "EMP012",
    "name": "Benjamin Lewis",
    "phone": "+1-202-555-0128",
    "email": "benjamin.lewis@example.com",
    "address": "369 Cherry Lane, Phoenix, AZ, USA",
    "jobTitle": "System Administrator",
    "department": "IT",
    "joiningDate": "2021-09-13",
    "isPresentToday": true,
    "salary": 82000,
    "manager": "Daniel Harris",
    "photo": "https://randomuser.me/api/portraits/men/12.jpg"
  },
  {
    "id": "EMP013",
    "name": "Mia Scott",
    "phone": "+1-202-555-0144",
    "email": "mia.scott@example.com",
    "address": "147 Magnolia Blvd, Portland, OR, USA",
    "jobTitle": "Financial Analyst",
    "department": "Finance",
    "joiningDate": "2020-04-27",
    "isPresentToday": true,
    "salary": 78000,
    "manager": "David Wilson",
    "photo": "https://randomuser.me/api/portraits/women/13.jpg"
  },
  {
    "id": "EMP014",
    "name": "Henry Walker",
    "phone": "+1-202-555-0198",
    "email": "henry.walker@example.com",
    "address": "753 Sycamore St, San Jose, CA, USA",
    "jobTitle": "QA Engineer",
    "department": "Engineering",
    "joiningDate": "2019-02-14",
    "isPresentToday": true,
    "salary": 71000,
    "manager": "Alice Johnson",
    "photo": "https://randomuser.me/api/portraits/men/14.jpg"
  },
  {
    "id": "EMP015",
    "name": "Charlotte King",
    "phone": "+1-202-555-0177",
    "email": "charlotte.king@example.com",
    "address": "951 Redwood Ave, Tampa, FL, USA",
    "jobTitle": "Operations Coordinator",
    "department": "Operations",
    "joiningDate": "2021-05-30",
    "isPresentToday": true,
    "salary": 65000,
    "manager": "Emma Thompson",
    "photo": "https://randomuser.me/api/portraits/women/15.jpg"
  },
  {
    "id": "EMP016",
    "name": "Jack Hall",
    "phone": "+1-202-555-0139",
    "email": "jack.hall@example.com",
    "address": "357 Poplar Rd, Atlanta, GA, USA",
    "jobTitle": "Technical Lead",
    "department": "Engineering",
    "joiningDate": "2017-11-22",
    "isPresentToday": false,
    "salary": 110000,
    "manager": "Robert Smith",
    "photo": "https://randomuser.me/api/portraits/men/16.jpg"
  },
  {
    "id": "EMP017",
    "name": "Amelia Young",
    "phone": "+1-202-555-0155",
    "email": "amelia.young@example.com",
    "address": "258 Cypress Lane, Houston, TX, USA",
    "jobTitle": "Legal Advisor",
    "department": "Legal",
    "joiningDate": "2019-08-19",
    "isPresentToday": true,
    "salary": 90000,
    "manager": "N/A",
    "photo": "https://randomuser.me/api/portraits/women/17.jpg"
  },
  {
    "id": "EMP018",
    "name": "Ethan Allen",
    "phone": "+1-202-555-0115",
    "email": "ethan.allen@example.com",
    "address": "654 Aspen Rd, Philadelphia, PA, USA",
    "jobTitle": "Data Scientist",
    "department": "Business Intelligence",
    "joiningDate": "2022-01-09",
    "isPresentToday": true,
    "salary": 99000,
    "manager": "James Anderson",
    "photo": "https://randomuser.me/api/portraits/men/18.jpg"
  },
  {
    "id": "EMP019",
    "name": "Harper Nelson",
    "phone": "+1-202-555-0182",
    "email": "harper.nelson@example.com",
    "address": "852 Juniper St, Minneapolis, MN, USA",
    "jobTitle": "Training Coordinator",
    "department": "Human Resources",
    "joiningDate": "2020-06-16",
    "isPresentToday": false,
    "salary": 64000,
    "manager": "Michael Brown",
    "photo": "https://randomuser.me/api/portraits/women/19.jpg"
  },
  {
    "id": "EMP020",
    "name": "Lucas Carter",
    "phone": "+1-202-555-0161",
    "email": "lucas.carter@example.com",
    "address": "951 Spruce Ave, Charlotte, NC, USA",
    "jobTitle": "Network Engineer",
    "department": "IT",
    "joiningDate": "2021-12-21",
    "isPresentToday": true,
    "salary": 86000,
    "manager": "Benjamin Lewis",
    "photo": "https://randomuser.me/api/portraits/men/20.jpg"
  }
]